In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.preprocessing import StandardScaler

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/xh/dlr59jp10wj5hx57q_rhfy3c0000gn/T/ipykernel_22349/4201554597.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py", line 52, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.12/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/xh/dlr59jp10wj5hx57q_rhfy3c0000gn/T/ipykernel_22349/4201554597.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py", line 66, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py", line 61, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.12/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

KeyboardInterrupt:

In [1]:
def load_meal_demand_dataset(file_name, data_path="data/"):
    print('Loading dataset')
    file_path = Path(data_path) / file_name
    df = pd.read_csv(file_path)
    print(f"Loaded {len(df)} rows from {file_path}")
    print(df.dtypes)
    print(df.describe())
    print(df)
    print("Done loading dataset")
    print("-------------------------------------------------------------")

    print("Cleaning dataset")
    df = parse_num_orders(df)
    df = clean_num_orders(df)
    df = remove_low_temporal_coverage(df)
    print("Done cleaning dataset")
    print("-------------------------------------------------------------")

    return df

def parse_num_orders(df):
    print(f"Length before parsing num_orders: {len(df)}")
    nulls = df['num_orders'].isnull()
    df = df[~nulls].copy() # this is a business decision as we don't normally do this without consulting the client.
    # instead of just dropping them, we could have performed forward filling for that specific city, meal category or meal type.
    df['num_orders']= df['num_orders'].str.replace(",", "")
    df['num_orders'] = pd.to_numeric(df['num_orders'])
    print(f"Length after parsing num_orders: {len(df)}")
    return df

def clean_num_orders(df):
    print(f"Length before cleaning num_orders: {len(df)}")
    max_value = 6.902760e+03
    negative_orders = df['num_orders'] < 0
    zero_orders = df['num_orders'] == 0 
    huge_orders = df['num_orders'] > max_value
    df = df[~(negative_orders | zero_orders | huge_orders)].copy()
    print(f"Length after cleaning num_orders: {len(df)}")
    return df

def remove_low_temporal_coverage(df): 
    print(f"Length before removing low temporal coverage records: {len(df)}")
    df = df[~(df['city_name'] == 'Osprey Point')].copy()
    print(f"Length after removing low temporal coverage records: {len(df)}")
    return df

In [1]:
df = load_meal_demand_dataset("meal_demand_historical.csv")

NameError: name 'load_meal_demand_dataset' is not defined

In [3]:
df

NameError: name 'df' is not defined

In [5]:
from sklearn.preprocessing import OneHotEncoder
meal_info_ohe = OneHotEncoder()
meal_info_ohe.fit(df[["meal_category", "meal_type"]].values)

NameError: name 'df' is not defined

In [ ]:
ohe_vals = meal_info_ohe.transform(df[["meal_category", "meal_type"]].values)

In [8]:
ohe_vals.toarray()

NameError: name 'ohe_vals' is not defined

In [10]:
ohe_vals.toarray()[2821]

NameError: name 'ohe_vals' is not defined

In [12]:
meal_info_ohe.inverse_transform([ohe_vals.toarray()[2821]])

NameError: name 'ohe_vals' is not defined

In [14]:
dir(meal_info_ohe)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_check_X',
 '_check_feature_names',
 '_check_get_feature_name_combiner',
 '_check_infrequent_enabled',
 '_check_n_features',
 '_compute_n_features_outs',
 '_compute_transformed_categories',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_fit',
 '_fit_infrequent_category_mapping',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_identify_infrequent',
 '_map_drop_idx_to_infrequent',
 '_map_infrequent_categories',
 '_more_tags',
 '_parameter_constraints',
 '_remove_dropped_categories',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_drop_idx',
 '_sklearn_auto_wrap_output_keys',
 '_transform',
 '_validate_data',
 '_validate_params',
 'categories',
 'drop',
 'dtype',
 'feature_name_combiner',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'handle_unknown',
 'infrequent_categories_',
 'inverse_transform',
 'max_categories',
 'min_frequency',
 'set_output',
 'set_params',
 'sparse_output',
 'transform']

In [16]:
meal_info_ohe.categories_

AttributeError: 'OneHotEncoder' object has no attribute 'categories_'

In [18]:
def get_ohe_columns(ohe_encoder):
    columns = []
    for cols in ohe_encoder.categories_:
        columns.extend(list(cols))
    return columns

In [20]:
get_ohe_columns(meal_info_ohe)

AttributeError: 'OneHotEncoder' object has no attribute 'categories_'

In [22]:
pd.DataFrame(ohe_vals.toarray(), columns=get_ohe_columns(meal_info_ohe)).astype(int)

NameError: name 'pd' is not defined

In [24]:
df_ohe = pd.DataFrame(ohe_vals.toarray(), columns=get_ohe_columns(meal_info_ohe)).astype(int)

NameError: name 'pd' is not defined

In [26]:
pd.concat((df.reset_index(drop=True), df_ohe.reset_index(drop=True)), axis=1)

NameError: name 'pd' is not defined

In [ ]:
df.groupby('city_name')['num_orders'].sum().sort_values().reset_index().city_name.tolist()

In [ ]:
ordered_city_names = df.groupby('city_name')['num_orders'].sum().sort_values().reset_index().city_name.tolist()

In [ ]:
class OrderedCategoryEncoder:
    def __init__(self):
        self.categories_: list[str] = None
        self.category_map: dict[str: int] = None
        self.inverse_category_map: dict[int: str] = None

    def fit(self, ordered_categories: list[str]):
        self.categories_ = ordered_categories
        self.category_map = {category: i+1 for i, category in enumerate(ordered_categories)}
        self.inverse_category_map = {i+1: category for i, category in enumerate(ordered_categories)}


    def transform(self, values: list[str]) -> np.array:
        if set(values) - set(self.categories_):
            for value in values:
                print(f"{value} was not in the fit data")
            raise ValueError("New category found, cannot transform")
        return np.array([self.category_map[value] for value in values])

    def inverse_transform(self, values: list[str]) -> np.array:
        return np.array([self.inverse_category_map[value] for value in values])

In [ ]:
city_name_encoder = OrderedCategoryEncoder()
city_name_encoder.fit(ordered_city_names)
encoded_city_names = city_name_encoder.transform(df.city_name.values)

In [ ]:
df.groupby('meal_name').num_orders.sum().sort_values().reset_index().meal_name.tolist()

In [1]:
ordered_meal_name = df.groupby('meal_name').num_orders.sum().sort_values().reset_index().meal_name.tolist()

NameError: name 'df' is not defined

In [1]:
meal_name_encoder = OrderedCategoryEncoder()
meal_name_encoder.fit(ordered_meal_name)
encoded_meal_names = meal_name_encoder.transform(df.meal_name.values)

NameError: name 'OrderedCategoryEncoder' is not defined

In [3]:
encoded_meal_names.shape

NameError: name 'encoded_meal_names' is not defined

In [5]:
def encode_features(df):
    print("Encoding dataset")
    meal_info_ohe = OneHotEncoder()
    city_name_encoder = OrderedCategoryEncoder()
    meal_name_encoder = OrderedCategoryEncoder()
    df = apply_ohe_encoding(df, meal_info_ohe)
    df = apply_ordinal_encoding(df, city_name_encoder, meal_name_encoder)
    print("Done encoding dataset")
    print("------------------------------------------------------")

    artifacts = {}
    artifacts['meal_info'] = meal_info_ohe
    artifacts['city_name'] = city_name_encoder
    artifacts['meal_name'] = meal_name_encoder

    return df, artifacts

def get_ohe_columns(ohe_encoder):
    columns = []
    for cols in ohe_encoder.categories_:
        columns.extend(list(cols))
    return columns

def apply_ohe_encoding(df, meal_info_ohe):
    print("Applying one-hot-encoding to meal_category and meal_type")
    meal_info_ohe.fit(df[["meal_category", "meal_type"]].values)
    ohe_vals = meal_info_ohe.transform(df[["meal_category", "meal_type"]].values)
    df = pd.concat((df.reset_index(drop=True), df_ohe.reset_index(drop=True)), axis=1)
    df.drop(columns=['meal_category', 'meal_type'], inplace=True)
    return df

def apply_ordinal_encoding(df, city_name_encoder, meal_name_encoder):
    print('Applying ordered categorical encoding to city_name')
    ordered_city_names = df.groupby('city_name')['num_orders']\
    .sum().sort_values().reset_index().city_name.tolist()
    city_name_encoder.fit(ordered_city_names)
    df['city_id'] = city_name_encoder.transform(df.city_name.values)

    print('Applying ordered categorical encoding to meal_name')
    ordered_meal_name = df.groupby('meal_name').num_orders\
    .sum().sort_values().reset_index().meal_name.tolist()
    meal_name_encoder.fit(ordered_meal_name)
    df['meal_id'] = meal_name_encoder.transform(df.meal_name.values)
    df = df.drop(columns = ['city_name', 'meal_name'])

    return df

In [7]:
df, encoders = encode_features(df)

NameError: name 'df' is not defined

In [9]:
df

NameError: name 'df' is not defined

In [11]:
df.to_csv("data/full_clean_encoded.csv", index=False)

NameError: name 'df' is not defined

In [13]:
encoders.keys()

NameError: name 'encoders' is not defined

In [15]:
from pickle import dump

In [17]:
def store_encoders(encoders, artifact_path="artifacts"):
    Path(artifact_path).mkdir(exist_ok=True, parents=True)
    for name, obj in encoders.items():
        with open(Path(artifact_path) / f"{name}_encoder.pkl", 'wb') as f:
            dump(obj, f)

store_encoders(encoders)

NameError: name 'encoders' is not defined

### Transforming the numeric features (scaling):

In [19]:
def scale_features(df):
    print("--------------------------------------------")
    print("Scaling dataset")
    price_scaler = StandardScaler()
    df = apply_scaling(df, price_scaler)
    print("Done scaling")
    print("--------------------------------------------")
    
    artifacts = {}
    artifacts['price_scaler'] = price_scaler

    return df, artifacts

def apply_scaling(df, price_scaler):
    df[['base_price', 'checkout_price']] = price_scaler.fit_transform(df[['base_price', 'checkout_price']])
    return df

df, scalers = scale_features(df)
encoders.update(scalers)

NameError: name 'df' is not defined

In [21]:
df

NameError: name 'df' is not defined

In [23]:
def add_price_feature(df):
    print("Adding price feature")
    df['price_diff'] = df.base_price - df.checkout_price
    print("Done adding price feature")
    return df

In [25]:
df = add_price_feature(df)

NameError: name 'df' is not defined

In [27]:
store_encoders(encoders)

NameError: name 'encoders' is not defined

In [29]:
!ls artifacts

city_name_encoder.pkl    meal_name_encoder.pkl
meal_info_encoder.pkl    price_scaler_encoder.pkl

### Feature Engineering for Temporal Data

In [30]:
def apply_yearly_offset_by_month(month_num):
    if month_num <= 12:
        return month_num
    elif month_num <= 24:
        return month_num - 12
    elif month_num <= 36:
        return month_num - 24
    else:
        raise NoImplementationError(month_num)

In [33]:
def apply_yearly_offset_by_quarter(quater_num):
    if quater_num <= 4:
        return quater_num
    elif quater_num <= 8:
        return quater_num - 4
    elif quater_num <= 12:
        return quater_num - 8
    else:
        raise NoImplementationError(quater_num)

In [35]:
def add_calendar_features(df):
    print("Adding calendar features")
    df['year_num'] = (df.week_number // 52 + 1).astype(int)
    df['month_num'] = (df.week_number // (52/12) + 1).astype(int).apply(apply_yearly_offset_by_month)
    df['quarter_num'] = (df.week_number // (52/4) + 1).astype(int).apply(apply_yearly_offset_by_quarter)
    df['week_of_year'] = (df.week_number - 1) % 52 + 1
    df["week_sin"] = np.sin(2 * np.pi * df["week_of_year"] / 52)
    df["week_cos"] = np.cos(2 * np.pi * df["week_of_year"] / 52)
    print("Done adding calendar features")
    return df

In [37]:
df = add_calendar_features(df)

NameError: name 'df' is not defined

In [39]:
df

NameError: name 'df' is not defined

### Lag features and moving averages

In [41]:
g = ['city_id', 'meal_id']

In [43]:
df.sort_values("week_number", ascending=True).reset_index(drop=True).groupby(g).num_orders.shift(-1) #shifting through index

NameError: name 'df' is not defined

In [1]:
df[['week_number', 'city_id', 'meal_id', 'num_orders']].sort_values(['week_number', 'city_id', 'meal_id'])

NameError: name 'df' is not defined

In [387]:
def add_rolling_features(df):
    df = df.sort_values("week_number", ascending=True).copy()

    print("Adding rolling features")
    g = ['city_id', 'meal_id']

    df['next_week_num_orders'] = df.groupby(g).num_orders.shift(-1)

    df['num_orders_last_year'] = df.groupby(g).num_orders.shift(52)

    df['num_orders_last_week'] = df.groupby(g).num_orders.shift(1)

    df['num_orders_rolling_4_week'] = df.groupby(g).num_orders.rolling(4).mean().reset_index(drop=True)

    df['num_orders_rolling_16_week'] = df.groupby(g).num_orders.rolling(16).mean().reset_index(drop=True)

    df['num_orders_last_year_rolling_4_weeks'] = df.groupby(g).num_orders_rolling_4_week.shift(52)
    
    df['num_orders_last_year_rolling_4_weeks'] = df.groupby(g).num_orders_rolling_16_week.shift(52)

    df_nulls = df[df.isnull().any(axis=1)].copy()

    df = df.dropna().copy()

    print("Done adding rolling features")

    return df, df_nulls

In [389]:
df, df_nulls = add_rolling_features(df)

Adding rolling features
Done adding rolling features

In [395]:
df.reset_index(drop=True).sort_values('week_number')

,week_number,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,op_area,Meat,Other,Seafood,...,quater_num,year_num,week_sin,week_cos,next_week_num_orders,num_orders_last_year,num_orders_last_week,num_orders_rolling_4_week,num_orders_rolling_16_week,num_orders_last_year_rolling_4_weeks
0,53,-0.973013,-1.074679,0,0,620,7.0,0,0,0,...,1,2,0.120537,0.992709,271.0,555.0,406.0,341.25,226.3125,608.1875
424,53,-0.339004,-0.458904,0,0,350,5.3,0,1,0,...,1,2,0.120537,0.992709,323.0,244.0,175.0,24.00,34.8750,17.3750
425,53,-0.325924,-0.452680,0,0,258,5.3,0,0,0,...,1,2,0.120537,0.992709,283.0,311.0,379.0,27.00,35.7500,18.9375
426,53,-0.135604,-0.271570,0,0,284,5.3,0,0,0,...,1,2,0.120537,0.992709,350.0,701.0,431.0,23.25,24.4375,20.5000
427,53,-0.656205,-0.398347,0,1,810,3.8,0,0,0,...,1,2,0.120537,0.992709,378.0,527.0,755.0,23.25,39.8750,14.8750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202470,144,-0.072164,-0.211200,0,1,231,7.0,1,0,0,...,4,3,-0.992709,0.120537,162.0,161.0,229.0,425.00,556.3750,137.5625
202471,144,-0.034296,-0.175165,0,0,364,4.5,0,0,1,...,4,3,-0.992709,0.120537,270.0,216.0,418.0,652.00,822.4375,63.5625
202472,144,-0.008723,-0.157054,0,0,485,4.5,1,0,0,...,4,3,-0.992709,0.120537,540.0,366.0,432.0,652.00,785.3750,64.4375
202492,144,-0.275368,-0.404571,0,0,393,7.0,1,0,0,...,4,3,-0.992709,0.120537,325.0,1687.0,447.0,520.00,563.8125,197.5625
204015,144,-0.865557,-0.959975,0,0,107,2.9,0,0,0,...,4,3,-0.992709,0.120537,107.0,134.0,136.0,206.00,132.1250,470.8125

In [393]:
df_nulls

,week_number,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,op_area,Meat,Other,Seafood,...,quater_num,year_num,week_sin,week_cos,next_week_num_orders,num_orders_last_year,num_orders_last_week,num_orders_rolling_4_week,num_orders_rolling_16_week,num_orders_last_year_rolling_4_weeks
0,1,-1.277525,-1.255789,0,0,177,2.0,0,0,0,...,1,1,0.120537,0.992709,323.0,NaN,NaN,NaN,NaN,NaN
1898,1,0.663741,0.495316,0,0,865,7.0,1,0,0,...,1,1,0.120537,0.992709,514.0,NaN,NaN,462.25,609.5625,NaN
1899,1,-0.598716,-0.531348,1,0,998,7.0,0,0,1,...,1,1,0.120537,0.992709,946.0,NaN,NaN,357.50,595.9375,NaN
1900,1,-0.339004,-0.458904,0,0,271,7.0,1,0,0,...,1,1,0.120537,0.992709,148.0,NaN,NaN,317.25,595.1250,NaN
1901,1,-0.325924,-0.446457,0,0,350,7.0,0,1,0,...,1,1,0.120537,0.992709,432.0,NaN,NaN,253.25,588.3125,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444611,145,0.187745,0.036130,0,0,67,2.9,0,0,0,...,4,3,-0.970942,0.239316,NaN,53.0,68.0,577.00,590.6875,96.2500
444612,145,0.118157,-0.030090,0,0,69,2.9,0,0,1,...,4,3,-0.970942,0.239316,NaN,13.0,69.0,971.75,629.5000,94.5625
444613,145,-0.478376,-0.585308,0,0,257,2.9,0,0,0,...,4,3,-0.970942,0.239316,NaN,566.0,432.0,982.00,622.8125,96.5625
444615,145,-0.135604,-0.265346,0,0,297,2.9,0,0,1,...,4,3,-0.970942,0.239316,NaN,108.0,177.0,719.25,613.7500,92.0000
446731,145,-0.262484,-0.398534,0,0,162,4.5,1,0,0,...,4,3,-0.970942,0.239316,NaN,284.0,190.0,2116.25,2126.2500,64.4375

In [ ]:
from IPython.display import display

In [399]:
with pd.option_context("display.max_rows", 10000000):
    display(df.head(100))

,week_number,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,op_area,Meat,Other,Seafood,...,quater_num,year_num,week_sin,week_cos,next_week_num_orders,num_orders_last_year,num_orders_last_week,num_orders_rolling_4_week,num_orders_rolling_16_week,num_orders_last_year_rolling_4_weeks
154412,53,-0.973013,-1.074679,0,0,620,7.0,0,0,0,...,1,2,0.120537,0.992709,271.0,555.0,406.0,341.25,226.3125,608.1875
154411,53,-0.966669,-1.062418,0,0,486,7.0,1,0,0,...,1,2,0.120537,0.992709,512.0,404.0,501.0,351.75,221.3125,599.0000
154426,53,-0.078704,-0.204976,0,0,823,7.0,0,0,1,...,1,2,0.120537,0.992709,730.0,690.0,811.0,270.00,263.4375,428.0000
154418,53,0.739477,0.573611,0,0,554,7.0,1,0,0,...,1,2,0.120537,0.992709,217.0,865.0,472.0,260.25,251.9375,609.5625
154419,53,-0.256532,-0.374199,0,0,852,7.0,0,0,1,...,1,2,0.120537,0.992709,258.0,998.0,825.0,270.50,255.3750,595.9375
154420,53,-0.339004,-0.446457,0,0,216,7.0,1,0,0,...,1,2,0.120537,0.992709,162.0,271.0,163.0,284.00,257.0000,595.1250
154421,53,-0.332464,-0.452680,0,1,312,7.0,0,1,0,...,1,2,0.120537,0.992709,418.0,350.0,431.0,256.50,263.6875,588.3125
154427,53,-0.135800,-0.265533,0,0,446,7.0,0,0,0,...,1,2,0.120537,0.992709,337.0,647.0,405.0,236.75,255.9375,326.7500
154405,53,-1.379226,-1.297861,1,1,3268,7.0,0,0,0,...,1,2,0.120537,0.992709,2700.0,1958.0,2471.0,172.25,204.4375,448.0625
154394,53,2.268579,2.016268,0,0,189,3.9,0,1,0,...,1,2,0.120537,0.992709,136.0,339.0,270.0,207.00,205.7500,402.3125
154457,53,-1.156989,-1.243528,0,0,94,7.0,1,0,0,...,1,2,0.120537,0.992709,123.0,13.0,150.0,111.00,175.6250,416.1250
154458,53,-0.979553,-1.068455,0,0,647,7.0,1,0,0,...,1,2,0.120537,0.992709,512.0,782.0,528.0,118.00,173.0000,419.4375
154460,53,-0.909573,-0.839235,0,0,1485,7.0,0,0,0,...,1,2,0.120537,0.992709,539.0,1741.0,1108.0,166.00,180.7500,412.6250
154461,53,-0.275172,0.724536,0,1,1135,7.0,0,0,0,...,1,2,0.120537,0.992709,676.0,431.0,1026.0,193.25,182.5000,438.8125
154465,53,0.739477,0.579834,0,0,729,7.0,1,0,0,...,1,2,0.120537,0.992709,41.0,703.0,850.0,161.75,158.7500,437.1250
154466,53,-0.389560,-0.500790,0,0,810,7.0,0,0,1,...,1,2,0.120537,0.992709,338.0,1566.0,701.0,145.00,152.8750,432.9375
154468,53,-0.339004,-0.446457,0,0,258,7.0,0,1,0,...,1,2,0.120537,0.992709,162.0,177.0,230.0,168.50,152.8125,443.0000
154467,53,-0.325924,-0.458904,0,0,28,7.0,1,0,0,...,1,2,0.120537,0.992709,95.0,204.0,150.0,165.00,148.6875,461.5625
154432,53,-1.087597,-1.158823,0,0,338,7.0,0,0,0,...,1,2,0.120537,0.992709,393.0,620.0,541.0,291.00,263.6250,253.5000
154434,53,-0.599109,-0.700197,0,0,80,7.0,0,0,0,...,1,2,0.120537,0.992709,54.0,150.0,230.0,230.25,241.7500,321.7500
154437,53,2.275120,2.016268,0,0,215,7.0,0,0,0,...,1,2,0.120537,0.992709,122.0,215.0,121.0,138.75,223.1875,404.5625
154438,53,2.268579,2.022492,0,0,231,7.0,0,0,0,...,1,2,0.120537,0.992709,161.0,351.0,162.0,159.00,214.8125,505.7500
154439,53,2.268579,2.028716,0,0,365,7.0,0,1,0,...,1,2,0.120537,0.992709,204.0,418.0,568.0,149.50,212.4375,539.5000
154440,53,0.365377,1.648011,1,0,931,7.0,0,1,0,...,1,2,0.120537,0.992709,243.0,149.0,1188.0,186.25,212.4375,527.6250
154443,53,-0.745021,-0.839049,0,0,163,7.0,1,0,0,...,1,2,0.120537,0.992709,149.0,215.0,216.0,186.25,199.8125,508.9375
154315,53,-1.366341,-1.310122,1,1,1230,3.8,0,0,0,...,1,2,0.120537,0.992709,879.0,580.0,312.0,75.00,98.1250,133.8125
154316,53,-1.379226,-1.328233,1,1,1201,3.8,1,0,0,...,1,2,0.120537,0.992709,1000.0,539.0,445.0,61.00,93.0000,139.8125
154321,53,-0.973209,-1.062418,0,0,176,3.8,1,0,0,...,1,2,0.120537,0.992709,189.0,285.0,149.0,55.25,75.6875,169.3125
154322,53,-0.973209,-1.056194,0,0,352,3.8,0,0,0,...,1,2,0.120537,0.992709,230.0,256.0,351.0,71.75,74.8125,171.0000
154286,53,0.619137,0.459094,0,0,393,3.9,1,0,0,...,1,2,0.120537,0.992709,96.0,312.0,324.0,246.75,156.3750,118.2500
154287,53,-0.155028,-0.271383,0,0,391,3.9,0,0,1,...,1,2,0.120537,0.992709,310.0,539.0,431.0,145.75,156.4375,121.5000
154289,53,-0.325924,-0.446457,0,0,176,3.9,0,1,0,...,1,2,0.120537,0.992709,311.0,391.0,135.0,125.25,159.0000,120.6875
154290,53,-0.325924,-0.446457,0,0,189,3.9,0,0,0,...,1,2,0.120537,0.992709,188.0,243.0,162.0,108.25,153.0625,126.5625
154300,53,2.014819,1.774788,0,0,94,3.9,0,0,0,...,1,2,0.120537,0.992709,190.0,177.0,95.0,108.50,114.2500,119.7500
154301,53,2.021359,1.774788,0,0,217,3.9,0,0,0,...,1,2,0.120537,0.992709,271.0,419.0,202.0,125.25,118.5000,113.0000
154302,53,2.008279,1.781012,0,0,81,3.9,0,1,0,...,1,2,0.120537,0.992709,121.0,325.0,107.0,151.75,123.5000,108.8750
154303,53,0.365377,1.720642,1,0,242,3.9,0,1,0,...,1,2,0.120537,0.992709,82.0,28.0,1230.0,152.00,126.8750,114.8125
154296,53,-0.142144,-0.277794,0,0,177,3.9,0,0,0,...,1,2,0.120537,0.992709,231.0,1041.0,258.0,81.00,154.8750,129.1250
154361,53,-1.372685,-1.310122,1,1,3093,3.9,0,0,0,...,1,2,0.120537,0.992709,2148.0,769.0,1161.0,250.25,214.1875,118.3750
154362,53,-1.379226,-1.285600,1,0,2931,3.9,1,0,0,...,1,2,0.120537,0.992709,1689.0,756.0,1216.0,223.00,208.2500,111.6250
154363,53,-1.379422,-1.297674,1,0,1041,3.9,1,0,0,...,1,2,0.120537,0.992709,1014.0,203.0,581.0,199.00,208.1875,111.6250
154367,53,-0.966669,-1.068642,0,0,352,3.9,1,0,0,...,1,2,0.120537,0.992709,149.0,204.0,366.0,254.00,234.2500,98.9375
154368,53,-0.960325,-1.056381,0,0,472,3.9,0,0,0,...,1,2,0.120537,0.992709,149.0,474.0,514.0,244.25,239.3750,97.1250
154370,53,-0.300940,0.760944,0,1,985,3.9,0,0,0,...,1,2,0.120537,0.992709,796.0,527.0,825.0,193.25,230.1875,99.7500
154372,53,-0.281516,0.736796,0,1,1149,3.9,0,0,1,...,1,2,0.120537,0.992709,1201.0,1026.0,987.0,182.75,236.8750,109.8750
154375,53,-0.281516,-0.416645,0,0,539,3.9,0,0,1,...,1,2,0.120537,0.992709,190.0,1108.0,445.0,215.25,214.5625,108.9375
154369,53,-0.896885,-0.772828,0,0,1013,3.9,0,0,0,...,1,2,0.120537,0.992709,298.0,958.0,755.0,240.50,233.5000,100.5625
154344,53,-0.960521,-1.050344,0,0,257,3.8,0,1,0,...,1,2,0.120537,0.992709,230.0,230.0,433.0,252.75,285.5625,82.9375
154349,53,2.262039,2.028716,0,0,204,3.8,0,1,0,...,1,2,0.120537,0.992709,107.0,258.0,176.0,169.50,234.9375,100.6875
154580,53,-0.960325,-1.050157,0,0,161,1.9,0,0,0,...,1,2,0.120537,0.992709,26.0,42.0,42.0,341.50,365.6875,337.2500
154592,53,-0.275564,-0.386087,0,0,540,1.9,1,0,0,...,1,2,0.120537,0.992709,67.0,365.0,366.0,408.50,314.2500,243.5625
154593,53,-0.275564,-0.392310,0,0,257,1.9,0,0,0,...,1,2,0.120537,0.992709,121.0,269.0,148.0,402.25,304.2500,224.0000
154576,53,-1.366341,-1.285600,1,0,69,1.9,0,0,0,...,1,2,0.120537,0.992709,121.0,82.0,134.0,381.25,361.3125,307.5000
154653,53,-1.379422,-1.327859,1,1,1026,3.0,1,0,0,...,1,2,0.120537,0.992709,958.0,204.0,1012.0,189.25,162.8125,86.1875
154658,53,-0.986093,-1.068455,0,0,271,3.0,1,0,0,...,1,2,0.120537,0.992709,177.0,271.0,188.0,287.50,188.3750,82.0000
154659,53,-0.966669,-1.056194,0,0,337,3.0,0,0,0,...,1,2,0.120537,0.992709,96.0,352.0,393.0,277.00,189.1250,77.8750
154663,53,-0.275564,0.754721,0,0,661,3.0,0,0,1,...,1,2,0.120537,0.992709,647.0,323.0,744.0,152.75,195.2500,84.7500
154284,53,-0.053131,-0.199313,0,0,512,3.9,0,0,1,...,1,2,0.120537,0.992709,512.0,405.0,676.0,271.00,153.1250,104.8125
154638,53,2.262039,2.028716,0,0,82,3.5,0,0,0,...,1,2,0.120537,0.992709,95.0,242.0,94.0,67.25,111.5000,97.6250
154639,53,2.275120,2.028716,0,0,296,3.5,0,1,0,...,1,2,0.120537,0.992709,229.0,446.0,189.0,64.00,104.0000,101.7500
154506,53,-0.992241,-1.080529,0,0,244,4.0,0,0,0,...,1,2,0.120537,0.992709,177.0,325.0,324.0,236.25,273.5625,167.8750
154508,53,-0.097540,-0.235348,0,0,256,4.0,0,0,0,...,1,2,0.120537,0.992709,135.0,42.0,647.0,350.50,272.5000,179.5000
154503,53,-1.163529,-1.243528,0,0,82,4.0,0,0,1,...,1,2,0.120537,0.992709,54.0,136.0,121.0,222.50,281.9375,208.5000
154502,53,-1.531286,-1.599898,0,1,270,4.0,1,0,0,...,1,2,0.120537,0.992709,150.0,148.0,445.0,266.50,299.7500,178.2500
154485,53,2.268579,2.016268,0,0,175,7.0,0,0,0,...,1,2,0.120537,0.992709,81.0,150.0,161.0,294.25,291.5000,283.6875
154487,53,2.262039,2.016268,0,0,418,7.0,0,1,0,...,1,2,0.120537,0.992709,217.0,581.0,231.0,328.50,305.1250,284.5625
154488,53,0.358837,1.648011,1,1,1106,7.0,0,1,0,...,1,2,0.120537,0.992709,161.0,190.0,1121.0,341.50,306.0000,297.1875
154490,53,0.409589,1.660458,1,0,486,7.0,0,1,0,...,1,2,0.120537,0.992709,54.0,69.0,298.0,341.00,316.8750,288.0000
154491,53,-0.738481,-0.832825,0,0,150,7.0,1,0,0,...,1,2,0.120537,0.992709,136.0,176.0,134.0,344.50,319.4375,282.0625
154525,53,2.014819,1.781012,0,0,148,4.0,0,1,0,...,1,2,0.120537,0.992709,150.0,231.0,176.0,536.75,451.0000,201.8750
154554,53,-0.325924,-0.458904,0,0,13,3.8,0,1,0,...,1,2,0.120537,0.992709,82.0,67.0,67.0,299.75,426.1250,291.2500
154559,53,-0.332268,-0.452494,0,0,298,3.8,0,0,1,...,1,2,0.120537,0.992709,177.0,94.0,202.0,321.25,372.4375,287.6875
154560,53,-0.262484,-0.386087,0,0,501,3.8,1,0,0,...,1,2,0.120537,0.992709,392.0,392.0,270.0,284.00,357.2500,289.3750
154561,53,-0.275368,-0.404571,0,0,433,3.8,0,0,0,...,1,2,0.120537,0.992709,377.0,769.0,297.0,310.75,354.6250,318.0625
154552,53,-0.389364,-0.271570,0,0,107,3.8,0,0,1,...,1,2,0.120537,0.992709,123.0,204.0,216.0,313.75,415.3125,293.8125
154566,53,2.021359,1.787235,0,0,80,3.8,0,0,0,...,1,2,0.120537,0.992709,95.0,150.0,69.0,399.00,347.8125,313.0000
154567,53,2.008279,1.774788,0,0,135,3.8,0,1,0,...,1,2,0.120537,0.992709,28.0,161.0,55.0,365.25,342.8750,308.6875
154551,53,0.473421,0.301759,0,0,109,3.8,1,0,0,...,1,2,0.120537,0.992709,69.0,270.0,134.0,402.00,420.5000,294.6875
154538,53,-1.531286,-1.599525,0,1,459,3.8,0,0,0,...,1,2,0.120537,0.992709,391.0,297.0,647.0,314.25,412.8125,274.3750
154544,53,-1.011077,-1.110901,0,0,136,3.8,1,0,0,...,1,2,0.120537,0.992709,123.0,122.0,122.0,610.75,426.9375,281.6875
154545,53,-1.011469,-1.092603,0,0,177,3.8,0,0,0,...,1,2,0.120537,0.992709,123.0,176.0,122.0,479.50,430.3125,290.1250
154546,53,-0.935341,-0.772828,0,0,123,3.8,0,0,0,...,1,2,0.120537,0.992709,122.0,188.0,163.0,425.75,435.4375,305.4375
154016,53,2.014819,1.781012,0,0,135,4.0,0,1,0,...,1,2,0.120537,0.992709,325.0,339.0,163.0,148.50,145.0000,219.0625
154017,53,0.365377,1.726865,1,1,338,4.0,0,1,0,...,1,2,0.120537,0.992709,15.0,123.0,593.0,149.00,146.8125,222.3125
154015,53,2.014819,1.774788,0,0,109,4.0,0,0,0,...,1,2,0.120537,0.992709,109.0,283.0,80.0,164.75,144.8750,217.3750
154029,53,-1.537826,-1.466897,0,1,635,3.0,0,0,0,...,1,2,0.120537,0.992709,730.0,230.0,878.0,44.00,67.9375,176.6875
154030,53,-1.556662,-1.472934,0,1,555,3.0,1,0,0,...,1,2,0.120537,0.992709,433.0,526.0,756.0,118.25,66.3125,187.8125
154032,53,-1.182561,-1.267863,0,0,67,3.0,0,0,1,...,1,2,0.120537,0.992709,80.0,42.0,81.0,189.00,78.0000,166.6250
154036,53,-0.922457,-1.014122,0,0,189,3.0,0,0,0,...,1,2,0.120537,0.992709,217.0,420.0,231.0,54.00,76.1250,185.1250
153995,53,-1.004733,-1.092416,0,0,243,4.0,0,0,0,...,1,2,0.120537,0.992709,123.0,297.0,229.0,37.50,71.9375,265.9375
154000,53,-0.440508,-0.543049,0,0,621,4.0,0,0,0,...,1,2,0.120537,0.992709,756.0,620.0,459.0,124.50,82.6875,231.2500
154001,53,0.473421,0.314206,0,0,188,4.0,1,0,0,...,1,2,0.120537,0.992709,67.0,296.0,339.0,124.50,77.5000,223.6875
154003,53,-0.339004,-0.452680,0,0,28,4.0,1,0,0,...,1,2,0.120537,0.992709,68.0,69.0,28.0,145.00,101.3125,185.8125
154005,53,-0.332464,-0.452680,0,0,95,4.0,0,0,0,...,1,2,0.120537,0.992709,148.0,108.0,96.0,151.75,95.2500,195.1875
154008,53,-0.345348,-0.458717,0,0,324,4.0,0,0,1,...,1,2,0.120537,0.992709,269.0,257.0,270.0,152.25,113.8125,222.1250
154038,53,-0.072164,-0.223274,0,1,366,3.0,1,0,0,...,1,2,0.120537,0.992709,297.0,701.0,743.0,43.50,76.7500,180.0625
154039,53,-0.084852,-0.235535,0,1,566,3.0,0,0,1,...,1,2,0.120537,0.992709,391.0,554.0,594.0,43.75,78.5000,196.0625
154068,53,-1.531286,-1.593488,0,0,257,4.0,0,0,0,...,1,2,0.120537,0.992709,365.0,284.0,433.0,74.25,61.7500,34.6875
154069,53,-1.544170,-1.599525,0,0,271,4.0,1,0,0,...,1,2,0.120537,0.992709,189.0,406.0,297.0,85.00,65.1250,35.5000
154074,53,-0.973405,-1.050157,0,0,55,4.0,1,0,0,...,1,2,0.120537,0.992709,94.0,81.0,40.0,50.50,54.0625,36.3125